-- MySQL Script generated by MySQL Workbench
-- Tue Aug 15 15:28:51 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema modelo MER
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `modelo MER` ;

-- -----------------------------------------------------
-- Schema modelo MER
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `modelo MER` DEFAULT CHARACTER SET utf8 ;
USE `modelo MER` ;

-- -----------------------------------------------------
-- Table `modelo MER`.`Finca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modelo MER`.`Finca` (
  `idFinca` INT NOT NULL,
  `tipo_evento` VARCHAR(20) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(100) NOT NULL,
  `ubicacion` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idFinca`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `modelo MER`.`Festival`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modelo MER`.`Festival` (
  `id_festival` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(100) NOT NULL,
  `fecha` VARCHAR(45) NOT NULL,
  `Finca_idFinca` INT NOT NULL,
  PRIMARY KEY (`id_festival`, `Finca_idFinca`),
  CONSTRAINT `fk_Festival_Finca1`
    FOREIGN KEY (`Finca_idFinca`)
    REFERENCES `modelo MER`.`Finca` (`idFinca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Festival_Finca1_idx` ON `modelo MER`.`Festival` (`Finca_idFinca` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `modelo MER`.`Rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modelo MER`.`Rol` (
  `id_rol` INT NOT NULL,
  `nombre_rol` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id_rol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `modelo MER`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modelo MER`.`Usuario` (
  `idUsuario` INT NOT NULL,
  `identificacion` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(20) NOT NULL,
  `correo` VARCHAR(30) NOT NULL,
  `contraseña` VARCHAR(45) NOT NULL,
  `Rol_id_rol` INT NOT NULL,
  PRIMARY KEY (`idUsuario`, `Rol_id_rol`),
  CONSTRAINT `fk_Usuario_Rol1`
    FOREIGN KEY (`Rol_id_rol`)
    REFERENCES `modelo MER`.`Rol` (`id_rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Usuario_Rol1_idx` ON `modelo MER`.`Usuario` (`Rol_id_rol` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `modelo MER`.`Tipo hospedaje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modelo MER`.`Tipo hospedaje` (
  `idTipo hospedaje` INT NOT NULL,
  `nombre_hospedaje` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTipo hospedaje`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `modelo MER`.`Hospedaje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modelo MER`.`Hospedaje` (
  `id_hospedaje` INT NOT NULL,
  `descripcion` VARCHAR(80) NOT NULL,
  `numero_camas` INT NOT NULL,
  `numero_noches` INT NOT NULL,
  `precio` DOUBLE NOT NULL,
  `Tipo hospedaje_idTipo hospedaje` INT NOT NULL,
  `Finca_idFinca` INT NOT NULL,
  PRIMARY KEY (`id_hospedaje`),
  CONSTRAINT `fk_Hospedaje_Tipo hospedaje1`
    FOREIGN KEY (`Tipo hospedaje_idTipo hospedaje`)
    REFERENCES `modelo MER`.`Tipo hospedaje` (`idTipo hospedaje`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Hospedaje_Finca1`
    FOREIGN KEY (`Finca_idFinca`)
    REFERENCES `modelo MER`.`Finca` (`idFinca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Hospedaje_Tipo hospedaje1_idx` ON `modelo MER`.`Hospedaje` (`Tipo hospedaje_idTipo hospedaje` ASC) VISIBLE;

CREATE INDEX `fk_Hospedaje_Finca1_idx` ON `modelo MER`.`Hospedaje` (`Finca_idFinca` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `modelo MER`.`Tipo recreacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modelo MER`.`Tipo recreacion` (
  `idTipo recreacion` INT NOT NULL,
  `nombre_recreacion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTipo recreacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `modelo MER`.`Recreacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modelo MER`.`Recreacion` (
  `id_recreacion` INT NOT NULL,
  `nombre` VARCHAR(30) NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `duracion` TIME NOT NULL,
  `disponibilidad` VARCHAR(15) NOT NULL,
  `cantidad_personas` INT NOT NULL,
  `precio` DOUBLE NOT NULL,
  `Tipo recreacion_idTipo recreacion` INT NOT NULL,
  `Finca_idFinca` INT NOT NULL,
  PRIMARY KEY (`id_recreacion`),
  CONSTRAINT `fk_Recreacion_Tipo recreacion1`
    FOREIGN KEY (`Tipo recreacion_idTipo recreacion`)
    REFERENCES `modelo MER`.`Tipo recreacion` (`idTipo recreacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Recreacion_Finca1`
    FOREIGN KEY (`Finca_idFinca`)
    REFERENCES `modelo MER`.`Finca` (`idFinca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Recreacion_Tipo recreacion1_idx` ON `modelo MER`.`Recreacion` (`Tipo recreacion_idTipo recreacion` ASC) VISIBLE;

CREATE INDEX `fk_Recreacion_Finca1_idx` ON `modelo MER`.`Recreacion` (`Finca_idFinca` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `modelo MER`.`Tipo charla`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modelo MER`.`Tipo charla` (
  `idTipo charla` INT NOT NULL,
  `nombre_charla` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTipo charla`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `modelo MER`.`Charla`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modelo MER`.`Charla` (
  `id_charla` INT NOT NULL,
  `nombre` VARCHAR(30) NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `duracion` TIME NOT NULL,
  `disponibilidad` VARCHAR(15) NOT NULL,
  `cantidad_personas` INT NOT NULL,
  `precio` DOUBLE NOT NULL,
  `Tipo charla_idTipo charla` INT NOT NULL,
  `Finca_idFinca` INT NOT NULL,
  PRIMARY KEY (`id_charla`),
  CONSTRAINT `fk_Charla_Tipo charla1`
    FOREIGN KEY (`Tipo charla_idTipo charla`)
    REFERENCES `modelo MER`.`Tipo charla` (`idTipo charla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Charla_Finca1`
    FOREIGN KEY (`Finca_idFinca`)
    REFERENCES `modelo MER`.`Finca` (`idFinca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Charla_Tipo charla1_idx` ON `modelo MER`.`Charla` (`Tipo charla_idTipo charla` ASC) VISIBLE;

CREATE INDEX `fk_Charla_Finca1_idx` ON `modelo MER`.`Charla` (`Finca_idFinca` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `modelo MER`.`Tipo taller`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modelo MER`.`Tipo taller` (
  `idTipo taller` INT NOT NULL,
  `nombre_taller` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTipo taller`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `modelo MER`.`Taller`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modelo MER`.`Taller` (
  `id_taller` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `duracion` TIME NOT NULL,
  `disponibilidad` VARCHAR(15) NOT NULL,
  `cantidad_personas` INT NOT NULL,
  `precio` DOUBLE NOT NULL,
  `Tipo taller_idTipo taller` INT NOT NULL,
  `Finca_idFinca` INT NOT NULL,
  PRIMARY KEY (`id_taller`),
  CONSTRAINT `fk_Taller_Tipo taller1`
    FOREIGN KEY (`Tipo taller_idTipo taller`)
    REFERENCES `modelo MER`.`Tipo taller` (`idTipo taller`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Taller_Finca1`
    FOREIGN KEY (`Finca_idFinca`)
    REFERENCES `modelo MER`.`Finca` (`idFinca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Taller_Tipo taller1_idx` ON `modelo MER`.`Taller` (`Tipo taller_idTipo taller` ASC) VISIBLE;

CREATE INDEX `fk_Taller_Finca1_idx` ON `modelo MER`.`Taller` (`Finca_idFinca` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `modelo MER`.`Reserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modelo MER`.`Reserva` (
  `id_Reserva` INT NOT NULL,
  `precio_total` DOUBLE NOT NULL,
  `fecha_inicio` DATETIME NOT NULL,
  `fecha_fin` DATETIME NOT NULL,
  `Usuario_idUsuario` INT NOT NULL,
  `Usuario_Rol_id_rol` INT NOT NULL,
  `Taller_id_taller` INT NOT NULL,
  `Charla_id_charla` INT NOT NULL,
  `Recreacion_id_recreacion` INT NOT NULL,
  `Hospedaje_id_hospedaje` INT NOT NULL,
  `Festival_id_festival` INT NOT NULL,
  `Festival_Finca_idFinca` INT NOT NULL,
  PRIMARY KEY (`id_Reserva`),
  CONSTRAINT `fk_Reserva_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario` , `Usuario_Rol_id_rol`)
    REFERENCES `modelo MER`.`Usuario` (`idUsuario` , `Rol_id_rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reserva_Taller1`
    FOREIGN KEY (`Taller_id_taller`)
    REFERENCES `modelo MER`.`Taller` (`id_taller`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reserva_Charla1`
    FOREIGN KEY (`Charla_id_charla`)
    REFERENCES `modelo MER`.`Charla` (`id_charla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reserva_Recreacion1`
    FOREIGN KEY (`Recreacion_id_recreacion`)
    REFERENCES `modelo MER`.`Recreacion` (`id_recreacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reserva_Hospedaje1`
    FOREIGN KEY (`Hospedaje_id_hospedaje`)
    REFERENCES `modelo MER`.`Hospedaje` (`id_hospedaje`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reserva_Festival1`
    FOREIGN KEY (`Festival_id_festival` , `Festival_Finca_idFinca`)
    REFERENCES `modelo MER`.`Festival` (`id_festival` , `Finca_idFinca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Reserva_Usuario1_idx` ON `modelo MER`.`Reserva` (`Usuario_idUsuario` ASC, `Usuario_Rol_id_rol` ASC) VISIBLE;

CREATE INDEX `fk_Reserva_Taller1_idx` ON `modelo MER`.`Reserva` (`Taller_id_taller` ASC) VISIBLE;

CREATE INDEX `fk_Reserva_Charla1_idx` ON `modelo MER`.`Reserva` (`Charla_id_charla` ASC) VISIBLE;

CREATE INDEX `fk_Reserva_Recreacion1_idx` ON `modelo MER`.`Reserva` (`Recreacion_id_recreacion` ASC) VISIBLE;

CREATE INDEX `fk_Reserva_Hospedaje1_idx` ON `modelo MER`.`Reserva` (`Hospedaje_id_hospedaje` ASC) VISIBLE;

CREATE INDEX `fk_Reserva_Festival1_idx` ON `modelo MER`.`Reserva` (`Festival_id_festival` ASC, `Festival_Finca_idFinca` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
